# Generated by Django 2.2.2 on 2020-01-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_new_new_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
