# Generated by Django 2.2.2 on 2020-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200123_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
